version: '3.8'
services:
    database:
        restart: always
        image: postgres:14.1-alpine
        environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=mysecretpassword
           - POSTGRES_DB=default_database
        ports: 
           - "5432:5432"
        volumes:
            - /data/postgresql:/var/lib/postgresql
            - /data/postgresql/data:/var/lib/postgresql/data
    backend:
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - database
    frontend:
        build: ./angular-training
        ports:
            - "8000:8000"
        depends_on:
            - backend
   